### ISSUE TITLE
Игнорирование через data-атрибут

### ISSUE THREAD

**Issue by dudeonthehorse** [nazarlitvin/gulp-utm2html#2]
Все здорово, спасибо за пакет. Забираю к себе в Kilogram.

Но в строчке ```if ($(links[i]).attr('data-utm') === 'nope')``` я бы использовал значение ```false``` или ```ignore``` – так намного семантичнее. Предлагаю добавить оба варианта с сохранением обратной совместимости.

**Comment by nazarlitvin** [comment]
@dudeonthehorse thanks, it makes sense, I'm going to update this ASAP.

**Comment by nazarlitvin** [comment]
Thanks, @drugoi for the PR #3 that provides this functionality. Now we can use one of these data-utm attributes for preventing URL change: nope, false and ignore. Updated version is already published to npm.
